# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c92b5becfaa8b50ef5d55f83815bc91380082293966cde158934f0e4bd1ac8755a28a24c2be4d08afb11fc72e4f53250ae53961c9e38dd7c38c33992cd73c34

test:
  secret_key_base: 65fba1b991260e773eb52cf8b6be2b9aa1c0913e3f03def0550aa8b3fa0c5dbd0d99e5d53ae93de98b8500bf3ee4cfa433dc7f98e6ddc541e182b2da570994f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
